// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJxK6yBshCLL-UgNeHwG2yWvV6Ts4hnOQ',
    appId: '1:628887508065:web:d152f110aefe1955300620',
    messagingSenderId: '628887508065',
    projectId: 'nutripet-840ac',
    authDomain: 'nutripet-840ac.firebaseapp.com',
    storageBucket: 'nutripet-840ac.firebasestorage.app',
    measurementId: 'G-Z7Z7P6CTF7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb-hYYHg9hfzW9o92guIn6FQ12oxmEDE0',
    appId: '1:628887508065:android:9492245d293c88b4300620',
    messagingSenderId: '628887508065',
    projectId: 'nutripet-840ac',
    storageBucket: 'nutripet-840ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK5A3zN7idwCTEGWVAE-nGitNXesB6whU',
    appId: '1:628887508065:ios:50b7980d216a6519300620',
    messagingSenderId: '628887508065',
    projectId: 'nutripet-840ac',
    storageBucket: 'nutripet-840ac.firebasestorage.app',
    iosBundleId: 'com.example.nutripet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK5A3zN7idwCTEGWVAE-nGitNXesB6whU',
    appId: '1:628887508065:ios:50b7980d216a6519300620',
    messagingSenderId: '628887508065',
    projectId: 'nutripet-840ac',
    storageBucket: 'nutripet-840ac.firebasestorage.app',
    iosBundleId: 'com.example.nutripet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJxK6yBshCLL-UgNeHwG2yWvV6Ts4hnOQ',
    appId: '1:628887508065:web:8020da0e236d8d54300620',
    messagingSenderId: '628887508065',
    projectId: 'nutripet-840ac',
    authDomain: 'nutripet-840ac.firebaseapp.com',
    storageBucket: 'nutripet-840ac.firebasestorage.app',
    measurementId: 'G-26LZEMPPDP',
  );
}
