import 'package:flutter/material.dart';

class FavoritesScreen extends StatelessWidget {
  const FavoritesScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text("Favoritos"),
                              ),
                                    body: Center(
                                            child: Padding(
                                                      padding: const EdgeInsets.all(24),
                                                                child: Column(
                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                                        children: const [
                                                                                                      Icon(
                                                                                                                      Icons.favorite_border,
                                                                                                                                      size: 100,
                                                                                                                                                      color: Colors.red,
                                                                                                                                                                    ),
                                                                                                                                                                                  SizedBox(height: 20),
                                                                                                                                                                                                Text(
                                                                                                                                                                                                                "Todavía no tienes alimentos favoritos.",
                                                                                                                                                                                                                                style: TextStyle(
                                                                                                                                                                                                                                                  fontSize: 18,
                                                                                                                                                                                                                                                                    fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                    textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                              Text(
                                                                                                                                                                                                                                                                                                                                                              "Cuando guardes un alimento aparecerá aquí.",
                                                                                                                                                                                                                                                                                                                                                                              textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                      }