import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});
  
    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text(
                                  "🐶 Nutripet",
                                            style: TextStyle(
                                                        fontWeight: FontWeight.bold,
                                                                  ),
                                                                          ),
                                                                                ),
                                                                                      body: SafeArea(
                                                                                              child: ListView(
                                                                                                        padding: const EdgeInsets.all(20),
                                                                                                                  children: [
                                                                                                                  
                                                                                                                              const Text(
                                                                                                                                            "¿Qué quieres hacer hoy?",
                                                                                                                                                          style: TextStyle(
                                                                                                                                                                          fontSize: 26,
                                                                                                                                                                                          fontWeight: FontWeight.bold,
                                                                                                                                                                                                        ),
                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                    
                                                                                                                                                                                                                                const SizedBox(height: 20),
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                            TextField(
                                                                                                                                                                                                                                                          decoration: InputDecoration(
                                                                                                                                                                                                                                                                          hintText: "Buscar alimento...",
                                                                                                                                                                                                                                                                                          prefixIcon: const Icon(Icons.search),
                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 20),
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                            ElevatedButton.icon(
                                                                                                                                                                                                                                                                                                                                                          onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                        icon: const Icon(Icons.qr_code_scanner),
                                                                                                                                                                                                                                                                                                                                                                                      label: const Text(
                                                                                                                                                                                                                                                                                                                                                                                                      "Escanear código de barras",
                                                                                                                                                                                                                                                                                                                                                                                                                      style: TextStyle(fontSize: 18),
                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 25),
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      leading: const Icon(Icons.pets, size: 35),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title: const Text("Mi mascota"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      subtitle: const Text("Añade el perfil de tu perro o gato"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      trailing: const Icon(Icons.arrow_forward_ios),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onTap: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 15),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      leading: const Icon(Icons.favorite, color: Colors.red),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title: const Text("Favoritos"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      subtitle: const Text("Tus productos guardados"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      trailing: const Icon(Icons.arrow_forward_ios),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onTap: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const SizedBox(height: 30),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "💡 Consejo del día",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style: TextStyle(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: 22,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Card(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: Padding(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    padding: EdgeInsets.all(18),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      "Haz el cambio de alimento de forma gradual durante 7 días para evitar problemas digestivos.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        style: TextStyle(fontSize: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }            }