import 'package:flutter/material.dart';

class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text("Mi mascota"),
                              ),
                                    body: Center(
                                            child: Padding(
                                                      padding: const EdgeInsets.all(24),
                                                                child: Column(
                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                                        children: const [
                                                                                                      CircleAvatar(
                                                                                                                      radius: 50,
                                                                                                                                      child: Icon(
                                                                                                                                                        Icons.pets,
                                                                                                                                                                          size: 50,
                                                                                                                                                                                          ),
                                                                                                                                                                                                        ),
                                                                                                                                                                                                                      SizedBox(height: 20),
                                                                                                                                                                                                                                    Text(
                                                                                                                                                                                                                                                    "Aún no has añadido ninguna mascota.",
                                                                                                                                                                                                                                                                    style: TextStyle(
                                                                                                                                                                                                                                                                                      fontSize: 20,
                                                                                                                                                                                                                                                                                                        fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                        textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                    SizedBox(height: 12),
                                                                                                                                                                                                                                                                                                                                                                                  Text(
                                                                                                                                                                                                                                                                                                                                                                                                  "En la próxima versión podrás crear el perfil de tu perro o gato.",
                                                                                                                                                                                                                                                                                                                                                                                                                  textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }