import 'package:flutter/material.dart';

class ScanScreen extends StatelessWidget {
  const ScanScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text("Escanear"),
                              ),
                                    body: Center(
                                            child: Padding(
                                                      padding: const EdgeInsets.all(24),
                                                                child: Column(
                                                                            mainAxisAlignment: MainAxisAlignment.center,
                                                                                        children: [
                                                                                                      const Icon(
                                                                                                                      Icons.qr_code_scanner,
                                                                                                                                      size: 120,
                                                                                                                                                    ),
                                                                                                                                                                  const SizedBox(height: 24),
                                                                                                                                                                                const Text(
                                                                                                                                                                                                "Escanea el código de barras de un alimento para mascotas.",
                                                                                                                                                                                                                textAlign: TextAlign.center,
                                                                                                                                                                                                                                style: TextStyle(fontSize: 18),
                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                            const SizedBox(height: 30),
                                                                                                                                                                                                                                                                          ElevatedButton.icon(
                                                                                                                                                                                                                                                                                          onPressed: () {
                                                                                                                                                                                                                                                                                                            ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                                                                                                                                                                                                                const SnackBar(
                                                                                                                                                                                                                                                                                                                                                      content: Text("El escáner llegará en la próxima versión 🚀"),
                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                            icon: const Icon(Icons.camera_alt),
                                                                                                                                                                                                                                                                                                                                                                                                                                            label: const Text("Abrir cámara"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }