import 'package:flutter/material.dart';

class LoginScreen extends StatelessWidget {
  const LoginScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text("Iniciar sesión"),
                              ),
                                    body: SafeArea(
                                            child: SingleChildScrollView(
                                                      padding: const EdgeInsets.all(24),
                                                                child: Column(
                                                                            crossAxisAlignment: CrossAxisAlignment.stretch,
                                                                                        children: [
                                                                                                      const SizedBox(height: 20),

                                                                                                                    const Icon(
                                                                                                                                    Icons.pets,
                                                                                                                                                    size: 80,
                                                                                                                                                                    color: Colors.green,
                                                                                                                                                                                  ),

                                                                                                                                                                                                const SizedBox(height: 16),

                                                                                                                                                                                                              const Text(
                                                                                                                                                                                                                              "Bienvenido a Nutripet",
                                                                                                                                                                                                                                              textAlign: TextAlign.center,
                                                                                                                                                                                                                                                              style: TextStyle(
                                                                                                                                                                                                                                                                                fontSize: 28,
                                                                                                                                                                                                                                                                                                  fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                ),

                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 8),

                                                                                                                                                                                                                                                                                                                                                            const Text(
                                                                                                                                                                                                                                                                                                                                                                            "Inicia sesión para guardar tus mascotas y favoritos.",
                                                                                                                                                                                                                                                                                                                                                                                            textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 35),

                                                                                                                                                                                                                                                                                                                                                                                                                                      OutlinedButton.icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      icon: const Icon(Icons.login),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      label: const Text("Continuar con Google"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 25),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  labelText: "Correo electrónico",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    prefixIcon: const Icon(Icons.email),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: BorderRadius.circular(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      obscureText: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        labelText: "Contraseña",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          prefixIcon: const Icon(Icons.lock),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: BorderRadius.circular(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 24),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            child: const Text("Iniciar sesión"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TextButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        child: const Text("¿Has olvidado tu contraseña?"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Row(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const Text("¿No tienes cuenta?"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        TextButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                child: const Text("Crear cuenta"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }