import 'package:flutter/material.dart';

class RegisterScreen extends StatelessWidget {
  const RegisterScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text("Crear cuenta"),
                              ),
                                    body: SafeArea(
                                            child: SingleChildScrollView(
                                                      padding: const EdgeInsets.all(24),
                                                                child: Column(
                                                                            crossAxisAlignment: CrossAxisAlignment.stretch,
                                                                                        children: [
                                                                                                      const SizedBox(height: 20),

                                                                                                                    const Icon(
                                                                                                                                    Icons.pets,
                                                                                                                                                    size: 80,
                                                                                                                                                                    color: Colors.green,
                                                                                                                                                                                  ),

                                                                                                                                                                                                const SizedBox(height: 16),

                                                                                                                                                                                                              const Text(
                                                                                                                                                                                                                              "Únete a Nutripet",
                                                                                                                                                                                                                                              textAlign: TextAlign.center,
                                                                                                                                                                                                                                                              style: TextStyle(
                                                                                                                                                                                                                                                                                fontSize: 28,
                                                                                                                                                                                                                                                                                                  fontWeight: FontWeight.bold,
                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                ),

                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 8),

                                                                                                                                                                                                                                                                                                                                                            const Text(
                                                                                                                                                                                                                                                                                                                                                                            "Crea una cuenta para guardar tus mascotas y favoritos.",
                                                                                                                                                                                                                                                                                                                                                                                            textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 30),

                                                                                                                                                                                                                                                                                                                                                                                                                                      OutlinedButton.icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      icon: const Icon(Icons.login),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      label: const Text("Registrarse con Google"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 20),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  labelText: "Nombre",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    prefixIcon: const Icon(Icons.person),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: BorderRadius.circular(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        labelText: "Correo electrónico",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          prefixIcon: const Icon(Icons.email),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: BorderRadius.circular(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 16),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            TextField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            obscureText: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            decoration: InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              labelText: "Contraseña",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                prefixIcon: const Icon(Icons.lock),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  border: OutlineInputBorder(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: BorderRadius.circular(12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const SizedBox(height: 24),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ElevatedButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onPressed: () {},
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  child: const Text("Crear cuenta"),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }